// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: users.proto

package protos;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.Empty)
    com.google.protobuf.MessageOrBuilder {
}
