// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: users.proto

package protos;

public interface LikeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.LikeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 user_id = 1;</code>
   * @return The userId.
   */
  int getUserId();

  /**
   * <code>int32 recipeId = 2;</code>
   * @return The recipeId.
   */
  int getRecipeId();
}
