// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: users.proto

package protos;

public interface RecipeResponse1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.RecipeResponse1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .protos.Recipe1 recipes = 1;</code>
   */
  java.util.List<protos.Recipe1> 
      getRecipesList();
  /**
   * <code>repeated .protos.Recipe1 recipes = 1;</code>
   */
  protos.Recipe1 getRecipes(int index);
  /**
   * <code>repeated .protos.Recipe1 recipes = 1;</code>
   */
  int getRecipesCount();
  /**
   * <code>repeated .protos.Recipe1 recipes = 1;</code>
   */
  java.util.List<? extends protos.Recipe1OrBuilder> 
      getRecipesOrBuilderList();
  /**
   * <code>repeated .protos.Recipe1 recipes = 1;</code>
   */
  protos.Recipe1OrBuilder getRecipesOrBuilder(
      int index);
}
