// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recipes.proto

package protos;

public interface RecipeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RecipeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Recipe recipes = 1;</code>
   */
  java.util.List<protos.Recipe> 
      getRecipesList();
  /**
   * <code>repeated .Recipe recipes = 1;</code>
   */
  protos.Recipe getRecipes(int index);
  /**
   * <code>repeated .Recipe recipes = 1;</code>
   */
  int getRecipesCount();
  /**
   * <code>repeated .Recipe recipes = 1;</code>
   */
  java.util.List<? extends protos.RecipeOrBuilder> 
      getRecipesOrBuilderList();
  /**
   * <code>repeated .Recipe recipes = 1;</code>
   */
  protos.RecipeOrBuilder getRecipesOrBuilder(
      int index);
}
