// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recipes.proto

package protos;

public interface RecipeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RecipeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ingredient = 1;</code>
   * @return The ingredient.
   */
  java.lang.String getIngredient();
  /**
   * <code>string ingredient = 1;</code>
   * @return The bytes for ingredient.
   */
  com.google.protobuf.ByteString
      getIngredientBytes();
}
