// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recipes.proto

package protos;

public interface RecipeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Recipe)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 user_id = 1;</code>
   * @return The userId.
   */
  int getUserId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string ingredients = 3;</code>
   * @return The ingredients.
   */
  java.lang.String getIngredients();
  /**
   * <code>string ingredients = 3;</code>
   * @return The bytes for ingredients.
   */
  com.google.protobuf.ByteString
      getIngredientsBytes();

  /**
   * <code>string description = 4;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 4;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>bool status = 5;</code>
   * @return The status.
   */
  boolean getStatus();
}
