// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recipes.proto

package via.sep3.grpc.proto;

public final class Recipes {
  private Recipes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RecipeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RecipeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RecipeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RecipeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rrecipes.proto\"#\n\rRecipeRequest\022\022\n\ningr" +
      "edient\030\001 \001(\t\"!\n\016RecipeResponse\022\017\n\007recipe" +
      "s\030\001 \001(\t2?\n\014RecipeFinder\022/\n\nGetRecipes\022\016." +
      "RecipeRequest\032\017.RecipeResponse\"\000B\027\n\023via." +
      "sep3.grpc.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RecipeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RecipeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RecipeRequest_descriptor,
        new java.lang.String[] { "Ingredient", });
    internal_static_RecipeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RecipeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RecipeResponse_descriptor,
        new java.lang.String[] { "Recipes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
