// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recipes.proto

package via.sep3.grpc.proto;

public interface RecipeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RecipeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string recipes = 1;</code>
   * @return The recipes.
   */
  java.lang.String getRecipes();
  /**
   * <code>string recipes = 1;</code>
   * @return The bytes for recipes.
   */
  com.google.protobuf.ByteString
      getRecipesBytes();
}
